# Video Storage Configuration Example
# Copy this file to config.toml and modify as needed

# Server configuration
listen_on_port = 32145            # Port to listen on
internal_addr = "127.0.0.1:32146" # Internal API address to bind to
permits = 5                       # Number of concurrent conversion jobs
token_rate = 0.0                  # Token bucket rate limiting (0.0 = disabled)
workspace = "./data"              # Working directory for file storage

# Storage backend configuration
storage_backend = "local"         # Storage backend: "local" or "s3"

# S3 configuration (only required when storage_backend = "s3")
# Uncomment and configure the following lines for S3/MinIO storage
# s3_bucket = "video-storage"             # S3 bucket name
# s3_endpoint = "http://localhost:9000"   # S3 endpoint (for MinIO or custom S3)
# s3_region = "us-east-1"                 # AWS region
# s3_access_key_id = "minioadmin"         # S3 access key ID
# s3_secret_access_key = "minioadmin"     # S3 secret access key

# Webhook configuration (optional)
# Uncomment to enable webhook notifications when jobs complete
# webhook_url = "https://example.com/webhook"  # Webhook endpoint URL

# Claim signing keys configuration (optional)
# If not specified, keys will be randomly generated on startup
# Format: kid = "base64_encoded_32_byte_key"
# You can generate a key with: openssl rand -base64 32
# [claim_keys]
# 1 = "IaNHoHtWetGMPkHj6Iy8MZe5L3KlH8F6j6nRvJpYQYU="
# 2 = "uBhfVeH0b7KQKfwOJqhwzLXKBpg7xLPBe5HjCksDDWg="

# ============================================================================
# Example configurations for different scenarios:
# ============================================================================

# === Local Storage Configuration ===
# Simple local file storage, no external dependencies
#
# listen_on_port = 32145
# internal_addr = "127.0.0.1:32146"
# permits = 5
# token_rate = 0.0
# workspace = "./data"
# storage_backend = "local"

# === MinIO Configuration ===
# For self-hosted MinIO object storage
#
# listen_on_port = 32145
# internal_addr = "127.0.0.1:32146"
# permits = 5
# token_rate = 0.0
# workspace = "./data"
# storage_backend = "s3"
# s3_bucket = "video-storage"
# s3_endpoint = "http://localhost:9000"
# s3_region = "us-east-1"
# s3_access_key_id = "minioadmin"
# s3_secret_access_key = "minioadmin"

# === AWS S3 Configuration ===
# For Amazon S3 cloud storage
#
# listen_on_port = 32145
# internal_addr = "127.0.0.1:32146"
# permits = 5
# token_rate = 0.0
# workspace = "./data"
# storage_backend = "s3"
# s3_bucket = "my-video-bucket"
# s3_region = "us-west-2"
# s3_access_key_id = "AKIAIOSFODNN7EXAMPLE"
# s3_secret_access_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

# === Production Configuration with Webhook ===
# Full production setup with S3 and webhook notifications
#
# listen_on_port = 8080
# internal_addr = "127.0.0.1:32146"
# permits = 10
# token_rate = 100.0
# workspace = "/var/lib/video-storage"
# storage_backend = "s3"
# s3_bucket = "production-videos"
# s3_region = "us-east-1"
# s3_access_key_id = "AKIAIOSFODNN7EXAMPLE"
# s3_secret_access_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
# webhook_url = "https://api.example.com/video-webhook"
# [claim_keys]
# 1 = "IaNHoHtWetGMPkHj6Iy8MZe5L3KlH8F6j6nRvJpYQYU="

# === Environment Variables ===
# You can also use environment variables for sensitive data:
# - S3_BUCKET
# - S3_ENDPOINT
# - AWS_REGION
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
#
# Environment variables will be used if the corresponding config values are not set
