# Video Storage Configuration Example
# Copy this file to config.toml and modify as needed

# Server configuration
listen_on_port = 32145          # Port to listen on
permits = 5                      # Number of concurrent conversion jobs
token_rate = 0.0                 # Token bucket rate limiting (0.0 = disabled)
workspace = "./data"             # Working directory for file storage

# Storage backend configuration
[storage]
backend = "local"                # Storage backend: "local" or "s3"

# S3 configuration (only required when backend = "s3")
# Uncomment and configure the following section for S3/MinIO storage
# [storage.s3]
# bucket = "video-storage"             # S3 bucket name
# endpoint = "http://localhost:9000"   # S3 endpoint (for MinIO or custom S3)
# region = "us-east-1"                 # AWS region
# access_key_id = "minioadmin"        # S3 access key ID
# secret_access_key = "minioadmin"    # S3 secret access key

# Webhook configuration (optional)
# Uncomment to enable webhook notifications when jobs complete
# [webhook]
# url = "https://example.com/webhook"  # Webhook endpoint URL
# timeout_seconds = 10                  # Request timeout in seconds

# Example configurations for different scenarios:

# === Local Storage Configuration ===
# Simple local file storage, no external dependencies
#
# [storage]
# backend = "local"

# === MinIO Configuration ===
# For self-hosted MinIO object storage
#
# [storage]
# backend = "s3"
#
# [storage.s3]
# bucket = "video-storage"
# endpoint = "http://localhost:9000"
# region = "us-east-1"
# access_key_id = "minioadmin"
# secret_access_key = "minioadmin"

# === AWS S3 Configuration ===
# For Amazon S3 cloud storage
#
# [storage]
# backend = "s3"
#
# [storage.s3]
# bucket = "my-video-bucket"
# region = "us-west-2"
# access_key_id = "AKIAIOSFODNN7EXAMPLE"
# secret_access_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

# === Production Configuration with Webhook ===
# Full production setup with S3 and webhook notifications
#
# listen_on_port = 8080
# permits = 10
# token_rate = 100.0
# workspace = "/var/lib/video-storage"
#
# [storage]
# backend = "s3"
#
# [storage.s3]
# bucket = "production-videos"
# region = "us-east-1"
# access_key_id = "${AWS_ACCESS_KEY_ID}"      # Use environment variable
# secret_access_key = "${AWS_SECRET_ACCESS_KEY}"  # Use environment variable
#
# [webhook]
# url = "https://api.example.com/video-webhook"
# timeout_seconds = 30
